core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('furn.urls')),
    path("dashboard/", include('dashboard.urls'), name='dashboard'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns (
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('furn.urls')),
    prefix_default_language = False
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

furn/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import *

app_name = 'furn'

urlpatterns = [
    path('', home, name="home"),
    path('signup/', signup, name='signup'),
    path('profile', profile, name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_redirect, name='logout-redirect'),
    path('logout-link', LogoutView.as_view(), name='logout-link'),
    path('<int:pk>/details/', arrivals_detail, name='arrival_detail'),
    path('rate-image/', rate_img, name='rate'),
]

templates/includes/blog.html
{% load static %}
<section id="blog" class="blog">
    <div class="container">
        <div class="section-header">
            <h2>latest blog</h2>
        </div>
        <!--/.section-header-->
        <div class="blog-content">
            <div class="row">
                {% for y in blog %}
                <div class="col-sm-4">
                    <div class="single-blog">
                        <div class="single-blog-img">
                            <img src="{{ y.img.url }}" alt="blog image" style="width: 400px;" >
                            <div class="single-blog-img-overlay"></div>
                        </div>
                        <div class="single-blog-txt">
                            <h2><a href="{{ y.title_url }}">{{ y.title }}</a></h2>
                            <h3>{{ y.date }}</h3>
                            <p>
                               {{ y.aboute }}
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!--/.container-->

</section>

templates/includes/carousel.html
{% load static %}

    <div id="header-carousel" class="carousel slide carousel-fade" data-ride="carousel">
        <!--/.carousel-indicator -->
        <ol class="carousel-indicators">
            <li data-target="#header-carousel" data-slide-to="0" class="active"><span class="small-circle"></span>
            </li>
            <li data-target="#header-carousel" data-slide-to="1"><span class="small-circle"></span></li>
            <li data-target="#header-carousel" data-slide-to="2"><span class="small-circle"></span></li>
            <li data-target="#header-carousel" data-slide-to="3"><span class="small-circle"></span></li>
        </ol><!-- /ol-->
        <!--/.carousel-indicator -->

        <!--/.carousel-inner -->
        <div class="carousel-inner" role="listbox">
            <!-- .item -->
            <div class="item active">
                <div class="single-slide-item slide1">
                    <div class="container">
                        <div class="welcome-hero-content">
                            <div class="row">
                                <div class="col-sm-7">
                                    <div class="single-welcome-hero">
                                        <div class="welcome-hero-txt">
                                            <h4>Great Design Collection</h4>
                                            <h2>Valvet Accent Arm Chair</h2>
                                            <p>
                                                Lorem Ipsum Dolor Sit Amet, Consectetur Adipisicing Elit, Sed Do Eiuiana Smod Tempor Ut Labore Et Dolore Magna Aliqua. Ut Enim Ad Minim Veniam, Quis Nostrud Exercitation Ullamco Laboris Nisi Ut Aliquip.
                                            </p>
                                            <div class="packages-price">
                                                <p>
                                                    $ 465
                                                    <del>$ 565</del>
                                                </p>
                                            </div>
                                            <button class="btn-cart welcome-add-cart"
                                                onclick="window.location.href='#'">
                                                <span class="lnr lnr-plus-circle"></span>
                                                add <span>to</span> cart
                                            </button>
                                            <button class="btn-cart welcome-add-cart welcome-more-info"
                                                onclick="window.location.href='#'">
                                                more info
                                            </button>
                                        </div>
                                        <!--/.welcome-hero-txt-->
                                    </div>
                                    <!--/.single-welcome-hero-->
                                </div>
                                <!--/.col-->
                                <div class="col-sm-5">
                                    <div class="single-welcome-hero">
                                        <div class="welcome-hero-img">
                                            <img src="{% static 'images/slider/slider1.png' %}" alt="slider image" width="500">
                                        </div>
                                        <!--/.welcome-hero-txt-->
                                    </div>
                                    <!--/.single-welcome-hero-->
                                </div>
                                <!--/.col-->
                            </div>
                            <!--/.row-->
                        </div>
                        <!--/.welcome-hero-content-->
                    </div><!-- /.container-->
                </div><!-- /.single-slide-item-->

            </div><!-- /.item .active-->
             {% for y in base %}
            <div class="item">
                <div class="single-slide-item slide1">
                    <div class="container">
                        <div class="welcome-hero-content">
                            <div class="row">
                                <div class="col-sm-7">
                                    <div class="single-welcome-hero">
                                        <div class="welcome-hero-txt">
                                            <h4>{{ y.slider_title }}</h4>
                                            <h2>{{ y.title }}</h2>
                                            <p>
                                               {{ y.aboute }}
                                            </p>
                                            <div class="packages-price">
                                                <p>
                                                    $ {{ y.price }}
                                                    <del>$ {{ y.old_price }}</del>
                                                </p>
                                            </div>
                                            <button class="btn-cart welcome-add-cart"
                                                onclick="window.location.href='#'">
                                                <span class="lnr lnr-plus-circle"></span>
                                                add <span>to</span> cart
                                            </button>
                                            <button class="btn-cart welcome-add-cart welcome-more-info"
                                                onclick="window.location.href='#'">
                                                more info
                                            </button>
                                        </div>
                                        <!--/.welcome-hero-txt-->
                                    </div>
                                    <!--/.single-welcome-hero-->
                                </div>
                                <!--/.col-->
                                <div class="col-sm-5">
                                    <div class="single-welcome-hero">
                                        <div class="welcome-hero-img">
                                            <img src="{{ y.img.url }}" alt="slider image" width="500">
                                        </div>
                                        <!--/.welcome-hero-txt-->
                                    </div>
                                    <!--/.single-welcome-hero-->
                                </div>
                                <!--/.col-->
                            </div>
                            <!--/.row-->
                        </div>
                        <!--/.welcome-hero-content-->
                    </div><!-- /.container-->
                </div><!-- /.single-slide-item-->

            </div><!-- /.item .active-->
            {% endfor %}

        </div><!-- /.carousel-inner-->

    </div>

templates/includes/clients.html
{% load static %}
<section id="clients" class="clients">
    <div class="container">
        <div class="owl-carousel owl-theme" id="client">
            <div class="item">
                <a href="#">
                    <img src="{% static 'images/clients/c1.png' %}" alt="brand-image" />
                </a>
            </div>
            <!--/.item-->
            <div class="item">
                <a href="#">
                    <img src="{% static 'images/clients/c2.png' %}" alt="brand-image" />
                </a>
            </div>
            <!--/.item-->
            <div class="item">
                <a href="#">
                    <img src="{% static 'images/clients/c3.png' %}" alt="brand-image" />
                </a>
            </div>
            <!--/.item-->
            <div class="item">
                <a href="#">
                    <img src="{% static 'images/clients/c4.png' %}" alt="brand-image" />
                </a>
            </div>
            <!--/.item-->
            <div class="item">
                <a href="#">
                    <img src="{% static 'images/clients/c5.png' %}" alt="brand-image" />
                </a>
            </div>
            <!--/.item-->
        </div>
        <!--/.owl-carousel-->

    </div>
    <!--/.container-->

</section>

templates/includes/discover.html
{% load static %}

<section id="populer-products" class="populer-products">
    <div class="container">
        <div class="populer-products-content">
            <div class="row">
                <div class="col-md-3">
                    <div class="single-populer-products">
                        <div class="single-populer-product-img mt40">
                            <img src="{% static 'images/populer-products/p1.png' %}" alt="populer-products images">
                        </div>
                        <h2><a href="#">arm chair</a></h2>
                        <div class="single-populer-products-para">
                            <p>Nemo enim ipsam voluptatem quia volu ptas sit asperna aut odit aut fugit.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="single-populer-products">
                        <div class="single-inner-populer-products">
                            <div class="row">
                                <div class="col-md-4 col-sm-12">
                                    <div class="single-inner-populer-product-img">
                                        <img src="{% static 'images/populer-products/p2.png' %}"
                                            alt="populer-products images">
                                    </div>
                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <div class="single-inner-populer-product-txt">
                                        <h2>
                                            <a href="#">
                                                latest designed stool <span>and</span> chair
                                            </a>
                                        </h2>
                                        <p>
                                            Edi ut perspiciatis unde omnis iste natusina error sit voluptatem
                                            accusantium doloret mque laudantium, totam rem aperiam.
                                        </p>
                                        <div class="populer-products-price">
                                            <h4>Sales Start from <span>$99.00</span></h4>
                                        </div>
                                        <button class="btn-cart welcome-add-cart populer-products-btn"
                                            onclick="window.location.href='#'">
                                            discover more
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="single-populer-products">
                        <div class="single-populer-products">
                            <div class="single-populer-product-img">
                                <img src="{% static 'images/populer-products/p3.png' %}" alt="populer-products images">
                            </div>
                            <h2><a href="#">hanging lamp</a></h2>
                            <div class="single-populer-products-para">
                                <p>Nemo enim ipsam voluptatem quia volu ptas sit asperna aut odit aut fugit.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/.container-->

</section>

templates/includes/feature.html
{% load static %}
<style>
    * {
        margin: 0;
        padding: 0;
    }

    .rate {
        float: left;
        height: 46px;
        padding: 0 10px;
    }

    .rate:not(:checked)>input {
        position: absolute;
        top: -9999px;
    }

    .rate:not(:checked)>label {
        float: right;
        width: 1em;
        overflow: hidden;
        white-space: nowrap;
        cursor: pointer;
        font-size: 30px;
        color: #ccc;
    }

    .rate:not(:checked)>label:before {
        content: '★ ';
    }

    .rate>input:checked~label {
        color: #ffc700;
    }

    .rate:not(:checked)>label:hover,
    .rate:not(:checked)>label:hover~label {
        color: #deb217;
    }

    .rate>input:checked+label:hover,
    .rate>input:checked+label:hover~label,
    .rate>input:checked~label:hover,
    .rate>input:checked~label:hover~label,
    .rate>label:hover~input:checked~label {
        color: #c59b08;
    }

    /* Modified from: https://github.com/mukulkant/Star-rating-using-pure-css */
</style>
<section id="feature" class="feature">
    <div class="container">
        <div class="section-header">
            <h2>featured products</h2>
        </div>
        <!--/.section-header-->
        <div class="feature-content">
            <div class="row">
                {% for y in products %}
                <div class="col-sm-3">
                    <div class="single-feature">
                        <img src="{{ y.img.url }}" alt="feature image" width="300" >
                        <div class="single-feature-txt text-center">
                            <p>
                            <html>
                            
                            <head>
                                <meta charset="UTF-8">
                                <link rel="stylesheet" type="text/css" href="style.css">
                                <title>Star rating using pure CSS</title>
                            </head>
                            
                            <body>
                                <div class="rate">
                                    <input type="radio" id="star5" name="rate" value="5" />
                                    <label for="star5" title="text">5 stars</label>
                                    <input type="radio" id="star4" name="rate" value="4" />
                                    <label for="star4" title="text">4 stars</label>
                                    <input type="radio" id="star3" name="rate" value="3" />
                                    <label for="star3" title="text">3 stars</label>
                                    <input type="radio" id="star2" name="rate" value="2" />
                                    <label for="star2" title="text">2 stars</label>
                                    <input type="radio" id="star1" name="rate" value="1" />
                                    <label for="star1" title="text">1 star</label>
                                </div>
                            </body>
                            
                            </html>
                            </p>
                            <h3><a href="{{ y.products_url }}">{{ y.title }}</a></h3>
                            <h5>${{ y.price }}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
    <!--/.container-->

</section>

templates/includes/logout-coniform.html
{% load static %}
<div class="logout-coniform">
    <img src="{% static 'logo/logout-logo.png' %}" alt="error">
    <p>Coniform exit?
    </p>
    <button class="logout-navbar"><a href="{% url 'furn:logout-link' %}" class="btn btn-info btn-lg logout-button">
        <span class="glyphicon glyphicon-log-out"></span> Log out
    </a></button>
</div>

<style>
    .logout-coniform{
        left: 42%;
        width: 16%;
        top: 250px;
        z-index: 999;
        height: 300px;
        display: none;
        position: fixed;
        padding: 50px 30px;
        text-align: center;
        background-color: royalblue;
    }
    .logout-coniform h1{
        margin-top: 20px;
    }
    .logout-coniform *{
        color: white;
    }
    .logout-coniform img{
        width: 70px;
        margin-top: 10px;
        border-radius: 50%;
    }
    .logout-button{
        margin-top: 20px;
    }
    /* .logout-button:hover{
        margin: auto !important;
        padding: auto !important;
    } */
    .logout-coniform p{
        margin-top: 10px;
    }
</style>

templates/includes/navigation.html
{% load static %}
{% load i18n %}
<!--welcome-hero start -->
<header id="home" class="welcome-hero">

    <div class="top-area">
        <div class="header-area">
            <!-- Start Navigation -->
            <nav class="navbar navbar-default bootsnav  navbar-sticky navbar-scrollspy" data-minus-value-desktop="70"
                data-minus-value-mobile="55" data-speed="1000">

                <!-- Start Top Search -->
                <div class="top-search">
                    <div class="container">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            <form>
                            <input name="q" type="text" class="form-control" placeholder="Search">
                            <button>Search</button>
                            </form>
                            <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
                        </div>
                    </div>
                </div>
                <!-- End Top Search -->

                <div class="container">
                    <!-- Start Atribute Navigation -->
                    <div class="attr-nav">
                        <ul>
                            <li class="search">
                                <a href="#"><span class="lnr lnr-magnifier"></span></a>
                            </li>
                            <!--/.search-->
                            <li class="nav-setting">
                                <a href="#"><span class="lnr lnr-cog"></span></a>
                            </li>
                            <!--/.search-->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="lnr lnr-cart"></span>
                                    <span class="badge badge-bg-1">2</span>
                                </a>
                                <ul class="dropdown-menu cart-list s-cate">
                                    <li class="single-cart-list">
                                        <a href="#" class="photo"><img
                                                src="{% static 'images/collection/arrivals1.png' %} " class="cart-thumb"
                                                alt="image" /></a>
                                        <div class="cart-list-txt">
                                            <h6><a href="#">arm <br> chair</a></h6>
                                            <p>1 x - <span class="price">$180.00</span></p>
                                        </div>
                                        <!--/.cart-list-txt-->
                                        <div class="cart-close">
                                            <span class="lnr lnr-cross"></span>
                                        </div>
                                        <!--/.cart-close-->
                                    </li>
                                    <!--/.single-cart-list -->
                                    <li class="single-cart-list">
                                        <a href="#" class="photo"><img
                                                src="{% static 'images/collection/arrivals2.png' %}" class="cart-thumb"
                                                alt="image" /></a>
                                        <div class="cart-list-txt">
                                            <h6><a href="#">single <br> armchair</a></h6>
                                            <p>1 x - <span class="price">$180.00</span></p>
                                        </div>
                                        <!--/.cart-list-txt-->
                                        <div class="cart-close">
                                            <span class="lnr lnr-cross"></span>
                                        </div>
                                        <!--/.cart-close-->
                                    </li>
                                    <!--/.single-cart-list -->
                                    <li class="single-cart-list">
                                        <a href="#" class="photo"><img
                                                src="{% static 'images/collection/arrivals3.png' %}" class="cart-thumb"
                                                alt="image" /></a>
                                        <div class="cart-list-txt">
                                            <h6><a href="#">wooden arn <br> chair</a></h6>
                                            <p>1 x - <span class="price">$180.00</span></p>
                                        </div>
                                        <!--/.cart-list-txt-->
                                        <div class="cart-close">
                                            <span class="lnr lnr-cross"></span>
                                        </div>
                                        <!--/.cart-close-->
                                    </li>
                                    <!--/.single-cart-list -->
                                    <li class="total">
                                        <span>Total: $0.00</span>
                                        <button class="btn-cart pull-right" onclick="window.location.href='#'">view
                                            cart</button>
                                    </li>
                                </ul>
                            </li>
                            <!--/.dropdown-->
                        </ul>
                    </div>
                    <!--/.attr-nav-->
                    <!-- End Atribute Navigation -->

                    <!-- Start Header Navigation -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="{% url 'furn:home' %}">sine<span>mkt</span>.</a>

                    </div>
                    <!--/.navbar-header-->
                    <!-- End Header Navigation -->

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu-ui-design" id="navbar-menu">
                        <ul class="nav navbar-nav navbar-center" data-in="fadeInDown" data-out="fadeOutUp">
                            <li class="active"><a href="{% url 'furn:home' %}">{% trans "uy" %}</a></li>
                            <li class="scroll"><a href="#new-arrivals">{% trans 'yangi kelgan' %}</a></li>
                            <li class="scroll"><a href="#newsletter">{% trans 'aloqa' %}</a></li>
                            {% if not request.user.is_authenticated %}
                            <li><a href="{% url 'furn:signup' %}">Register</a></li>
                            <li><a href="{% url 'furn:login' %}">Login</a></li>
                            {% endif %}
                            {% if request.user.is_organiser %}
                            <li class=""><a href="/dashboard/">dashboard</a></li>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                            <li class="profile-navbar"><a href="{% url 'furn:profile' %}">Profile</a></li>
                            <li class="logout-navbar"><a href="#">Logout</a></li>
                            {% endif %}
                            
                        </ul>
                        <!--/.nav -->
                       
                    </div><!-- /.navbar-collapse -->
                </div>
                <!--/.container-->
           
            </nav>
            <!--/nav-->
            <!-- End Navigation -->
        </div>
        <!--/.header-area-->
        <div class="clearfix"></div>

    </div>

     

</header>
<!--/.welcome-hero-->
<!--welcome-hero end -->

templates/includes/new-arrivals.html
{% load static %}



<style>
    .links{
        padding: 10px;
        border: 1px solid aqua !important;
        text-decoration: none !important;
        display: inline-block !important;
        /* padding: 10px 15px !important; */
        margin-top: 40px;
        margin-left: 20px;
    }
    .links:hover{
        padding: 10px !important;
    }
</style>
<section id="new-arrivals" class="new-arrivals">
    <!-- container -->
    <div class="container">
        <div class="section-header">
            <h2>new arrivals</h2>
            <a class="links" href="{% url 'furn:home' %}">All</a>
            {% for category in categories %}
            <a class="links" href="{% url 'furn:home' %}?category={{ category.category_name }}">{{ category.category_name }}</a>
            {% endfor %}
        </div>
        <!--/.section-header-->
        <div class="new-arrivals-content">
            <div class="row">
                {% for y in arrivals %}
                <div class="col-md-3 col-sm-4">
                    <div class="single-new-arrival">
                        <div class="single-new-arrival-bg">
                            <img src="{{ y.arrivals_img.url }}" alt="new-arrivals images">
                            <div class="single-new-arrival-bg-overlay"></div>
                            <div class="new-arrival-cart">
                                <p>
                                    <span class="lnr lnr-cart"></span>
                                    <a href="#">add <span>to </span> cart</a>
                                </p>
                                <p class="arrival-review pull-right">
                                    <span class="lnr lnr-heart"></span>
                                    <span class="lnr lnr-frame-expand"></span>
                                </p>
                            </div>
                        </div>
                        <h4><a href="{% url 'furn:arrival_detail' y.pk %}">{{ y.arrivals_title }}</a></h4>
                        <p class="arrival-product-price">${{ y.arrivals_price }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!--/.container-->

</section>

templates/includes/rate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
</head>

<style>
    .checked {
        color: gold;
    }
</style>

<body>
    {% if rate %}
    <img src="{{ rate.image.url }}" alt="" width="500">
    <a href="{% url 'furn:home' %}"><button>Next</button></a>
    <form method="POST" class="rate-form" id="{{ rate.id }}">
        {% csrf_token %}
        <button type="submit" class="fa fa-star fa-3x btns" id="first"></button>
        <button type="submit" class="fa fa-star fa-3x btns" id="second"></button>
        <button type="submit" class="fa fa-star fa-3x btns" id="third"></button>
        <button type="submit" class="fa fa-star fa-3x btns" id="fourth"></button>
        <button type="submit" class="fa fa-star fa-3x btns " id="fifth"></button>
        <br>
        <div id="confirm-box"></div>
    </form>

    {% else %}
    <h1>There is no image to rate</h1>
    <button type="submit" class="fa fa-star fa-3x btns" id="bir"></button>
    <button type="submit" class="fa fa-star fa-3x btns" id="ikki"></button>
    <button type="submit" class="fa fa-star fa-3x btns" id="uch"></button>
    <button type="submit" class="fa fa-star fa-3x btns" id="tort"></button>
    <button type="submit" class="fa fa-star fa-3x btns " id="besh"></button>
    <h3 id="avg">{{ avg_rate.score__avg }}</h3>
    {% endif %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'main.js' %}"></script>
</body>

</html>